#!/usr/bin/env bash

set -e

# generate the helm chart
VERSION=$(speedmgmt helm)

# use the chart's README as this repo's README
cp "${VERSION}/README.md" .

# bundle it up
helm package "${VERSION}"

echo "
Excellent, you've built the helm chart from the latest version of speedmgmt.
Now we need to update speedscale/partner-charts and submit a PR to the upstream
rancher/partner-charts.

Update the fork branch of speedscale/partner-charts with 'git pull https://github.com/rancher/partner-charts main-source'

Details at https://github.com/rancher/partner-charts/tree/main-source.

The commands should look something like this:
$ vim packages/speedscale-operator/package.yaml
$ PACKAGE=speedscale-operator make prepare
$ make validate
$ # git commit and push one or more times
$ make validate
$ submit PR
"

