apiVersion: v1
data:
  CLUSTER_NAME: MY_CLUSTER
  CONTAINER_REGISTRY: gcr.io/speedscale
  CONTAINER_TYPE: {{ .Values.image.tag }}
  LOG_LEVEL: info
  SLACK_WEBHOOK_URL: ""
  SUB_TENANT_NAME: ""
  SUB_TENANT_STREAM: ""
  TELEMETRY_INTERVAL: "60"
  TELEMETRY_TEST_INTERVAL: "1"
  TENANT_BUCKET: ""
  TENANT_ID: ""
  TENANT_NAME: ""
  TENANT_REGION: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: speedscale-controller
  namespace: speedscale
