apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    control-plane: controller-manager
  name: speed-operator-controller-manager
  namespace: speedscale
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: speedscale-controller
        - secretRef:
            name: speedscale-apikey
            optional: true
        image: gcr.io/speedscale/speed-operator:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: speedscale-manager
        ports:
        - containerPort: 9443
          name: webhook-server
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: operator-cert
        - mountPath: /etc/ssl/speedscale
          name: ss-certs
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: speedscale-kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources: {}
      serviceAccountName: speedscale-control-sa
      terminationGracePeriodSeconds: 10
      volumes:
      - name: operator-cert
        secret:
          defaultMode: 420
          secretName: operator-cert
      - name: ss-certs
        secret:
          secretName: ss-certs
status: {}
