apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: speed-operator-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - jobs
  - namespaces
  - secrets
  - daemonsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - jobs
  - namespaces
  - pods
  - pods/log
  - secrets
  - services
  - serviceaccounts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - create
  - delete
  - deletecollection
  - use
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - deletecollection
  - list
  - update
  - watch
- apiGroups:
  - speedscale.com
  resources:
  - test-reports
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - delete
  - deletecollection
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: speed-operator-manager-rolebinding
  namespace: speedscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: speed-operator-manager-role
subjects:
- kind: ServiceAccount
  name: speedscale-control-sa
  namespace: speedscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: speed-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: speed-operator-proxy-rolebinding
  namespace: speedscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: speed-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: speedscale-control-sa
  namespace: speedscale
---
apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
- name: gcrcred
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: speedscale-control-sa
  namespace: speedscale
