---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: speedscale-operator
    controlplane.speedscale.com/component: operator
  name: speedscale-operator
  namespace: {{ .Release.Namespace }}
  {{- if .Values.globalAnnotations }}
  annotations: {{ toYaml .Values.globalAnnotations | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: speedscale-operator
    controlplane.speedscale.com/component: operator
status:
  loadBalancer: {}
