{{- $jobAnnotations := mergeOverwrite (deepCopy (default (dict) .Values.globalAnnotations)) (deepCopy (default (dict) .Values.preInstallJob.annotations)) (dict "helm.sh/hook" "pre-install" "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded" "helm.sh/hook-weight" "4") -}}
{{- $jobLabels := mergeOverwrite (deepCopy (default (dict) .Values.globalLabels)) (deepCopy (default (dict) .Values.preInstallJob.labels)) -}}
{{- $podAnnotations := mergeOverwrite (deepCopy (default (dict) .Values.globalAnnotations)) (deepCopy (default (dict) .Values.preInstallJob.podAnnotations)) -}}
{{- $podLabels := mergeOverwrite (deepCopy (default (dict) .Values.globalLabels)) (deepCopy (default (dict) .Values.preInstallJob.podLabels)) -}}
{{- $jobImageRegistry := .Values.preInstallJob.image.registry | default .Values.image.registry -}}
{{- $jobImageTag := .Values.preInstallJob.image.tag | default .Values.image.tag -}}
{{- $jobImagePullPolicy := .Values.preInstallJob.image.pullPolicy | default .Values.image.pullPolicy -}}
{{- $jobContainerSecurityContext := .Values.globalPodSecurityContext -}}
{{- if ne .Values.preInstallJob.containerSecurityContext nil -}}
{{- $jobContainerSecurityContext = .Values.preInstallJob.containerSecurityContext -}}
{{- end -}}
{{- $jobPodSecurityContext := .Values.globalSecurityContext -}}
{{- if ne .Values.preInstallJob.podSecurityContext nil -}}
{{- $jobPodSecurityContext = .Values.preInstallJob.podSecurityContext -}}
{{- end -}}
{{- $jobAffinity := .Values.affinity -}}
{{- if ne .Values.preInstallJob.affinity nil -}}
{{- $jobAffinity = .Values.preInstallJob.affinity -}}
{{- end -}}
{{- $jobTolerations := .Values.tolerations -}}
{{- if ne .Values.preInstallJob.tolerations nil -}}
{{- $jobTolerations = .Values.preInstallJob.tolerations -}}
{{- end -}}
{{- $jobNodeSelector := .Values.nodeSelector -}}
{{- if ne .Values.preInstallJob.nodeSelector nil -}}
{{- $jobNodeSelector = .Values.preInstallJob.nodeSelector -}}
{{- end -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    {{- if $jobAnnotations }}
{{ toYaml $jobAnnotations | indent 4}}
    {{- end }}
  creationTimestamp: null
  name: speedscale-operator-pre-install
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if $jobLabels }}
{{ toYaml $jobLabels | indent 4}}
    {{- end }}
spec:
  backoffLimit: {{ .Values.preInstallJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.preInstallJob.ttlSecondsAfterFinished }}
  template:
    metadata:
      annotations:
        {{- if $podAnnotations }}
{{ toYaml $podAnnotations | indent 8}}
        {{- end }}
      creationTimestamp: null
      labels:
        {{- if $podLabels }}
{{ toYaml $podLabels | indent 8}}
        {{- end }}
    spec:
      {{- if .Values.preInstallJob.serviceAccountName }}
      serviceAccountName: {{ .Values.preInstallJob.serviceAccountName }}
      {{- end }}
      containers:
      - args:
        - |-
          set -eou pipefail
          # ensure valid settings before the chart reports a successfull install
          {{- if .Values.http_proxy }}
          HTTP_PROXY={{ .Values.http_proxy | quote }} \
          {{- end }}
          {{- if .Values.https_proxy }}
          HTTPS_PROXY={{ .Values.https_proxy | quote }} \
          {{- end }}
          {{- if .Values.no_proxy }}
          NO_PROXY={{ .Values.no_proxy | quote }} \
          {{- end }}
          speedctl init --overwrite \
          --home /tmp/speedscale \
          --api-key $SPEEDSCALE_API_KEY \
          --app-url $SPEEDSCALE_APP_URL

          # in case we're in istio
          curl -X POST http://127.0.0.1:15000/quitquitquit || true
        command:
        - bash
        - -c
        envFrom:
        - secretRef:
            name: '{{ ne .Values.apiKeySecret "" | ternary .Values.apiKeySecret "speedscale-apikey" }}'
            optional: false
        {{- if .Values.preInstallJob.extraEnvFrom }}
{{ toYaml .Values.preInstallJob.extraEnvFrom | nindent 8 }}
        {{- end }}
        image: '{{ $jobImageRegistry }}/speedscale-cli:{{ $jobImageTag }}'
        imagePullPolicy: {{ $jobImagePullPolicy }}
        name: speedscale-cli
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        securityContext: {{ toYaml $jobContainerSecurityContext | nindent 10 }}
        resources: {{ toYaml .Values.preInstallJob.resources | nindent 10 }}
      restartPolicy: Never
      securityContext: {{ toYaml $jobPodSecurityContext | nindent 8 }}
      {{- if $jobAffinity }}
      affinity: {{ toYaml $jobAffinity | nindent 8 }}
      {{- end }}
      {{- if $jobTolerations }}
      tolerations: {{ toYaml $jobTolerations | nindent 8 }}
      {{- end }}
      {{- if $jobNodeSelector }}
      nodeSelector: {{ toYaml $jobNodeSelector | nindent 8 }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
