{{- if .Values.replayCoordinator.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
{{- with .Values.image.pullSecrets }}
imagePullSecrets: {{ toYaml . | nindent 2 }}
{{- end }}
metadata:
  name: speedscale-replay-coordinator
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- with .Values.globalLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    app: speedscale-replay-coordinator
    controlplane.speedscale.com/component: replay-coordinator
  {{- with .Values.globalAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
