#!/usr/bin/env bash
#
# Regenerates the S-12907 security-evidence pack from the CURRENT templates.
#
# Run this after any template change and commit the result. CI runs it and
# fails on a diff, so the pack cannot quietly describe a chart that no longer
# exists.
#
# Determinism: the only non-deterministic bytes in a default render are the
# TLS key pair, which genSignedCert generates fresh every time. Those three
# values are redacted -- both so the output is stable enough to diff, and
# because a private key has no business in a git repository even when it is a
# throwaway.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_DIR="$(dirname "$SCRIPT_DIR")"

RELEASE_NAME="speedscale"
RELEASE_NAMESPACE="speedscale"

redact() {
  sed -E 's#^(  (tls\.crt|tls\.key|ca\.crt)):[[:space:]]+.*#\1: <redacted by evidence/generate.sh -- regenerated on every render>#'
}

render() {
  local out=$1; shift
  {
    echo "# GENERATED by speedscale-namespaced/evidence/generate.sh -- DO NOT EDIT."
    echo "#"
    echo "# helm template $RELEASE_NAME <chart> --namespace $RELEASE_NAMESPACE $*"
    echo "#"
    echo "# TLS key material is redacted; everything else is verbatim."
    echo "---"
    helm template "$RELEASE_NAME" "$CHART_DIR" \
      --namespace "$RELEASE_NAMESPACE" "$@" | redact
  } > "$out"
  echo "wrote $(basename "$out") ($(grep -c '^kind:' "$out") objects)"
}

# The install a customer gets with no overrides at all.
render "$SCRIPT_DIR/rendered-default.yaml"

# Every optional feature on at once: JKS hook, NetworkPolicies, PDBs, the
# optional metrics and Lease RBAC. This is the widest grant the chart can
# produce, which is the one a security reviewer actually needs to see.
render "$SCRIPT_DIR/rendered-all-features.yaml" \
  --values "$CHART_DIR/tests/values/everything-enabled.yaml"
